java_library(
    name = "misc",
    srcs = glob(["*.java"]),
    visibility = [
        "//server/src/main/java/net/thisptr/phlegethon:__subpackages__",
    ],
    deps = [
        "@maven//:com_google_guava_guava",
    ],
)
