java_library(
    name = "blob",
    srcs = glob(["*.java"]),
    visibility = ["//server:__subpackages__"],
    deps = [
        "//server/src/main/java/net/thisptr/phlegethon/blob/types/jfr",
        "//server/src/main/java/net/thisptr/phlegethon/blob/types/perf",
    ],
)
