java_library(
    name = "blob",
    srcs = glob(["*.java"]),
    visibility = ["//server:__subpackages__"],
    deps = [
        "//server/src/main/java/net/thisptr/phlegethon/misc",
        "@maven//:joda_time_joda_time",
    ],
)
