java_library(
    name = "model",
    srcs = glob(["*.java"]),
    visibility = [
        "//server/src/main/java/net/thisptr/phlegethon:__subpackages__",
    ],
    deps = [
        "//server/src/main/java/net/thisptr/phlegethon/misc",
        "@maven//:com_fasterxml_jackson_core_jackson_annotations",
        "@maven//:com_google_guava_guava",
        "@maven//:joda_time_joda_time",
    ],
)
