java_library(
    name = "model",
    srcs = glob(["*.java"]),
    visibility = [
        "//server/src/main/java/net/thisptr/phlegethon:__subpackages__",
    ],
    deps = [
        # "//server/src/main/java/net/thisptr/phlegethon/storage",
        # "@maven//:org_springframework_spring_web",
        # "@maven//:com_fasterxml_jackson_core_jackson_databind",
        "@maven//:com_fasterxml_jackson_core_jackson_annotations",
    ],
)
