# java_library(
#     name = "tests",
# 	srcs = glob(["*Test.java"]),
# 	deps = [
#         "@maven//:junit_junit",
# 	],
# )
#
java_test(
    name = "ServerTest",
    srcs = ["ServerTest.java"],
    deps = [
        "@maven//:junit_junit",
    ],
)
