java_library(
    name = "sql",
    srcs = glob(["*.java"]),
    visibility = [
        "//server/src/main/java/net/thisptr/phlegethon:__subpackages__",
    ],
    deps = [
        "@maven//:org_slf4j_slf4j_api",
        # "//server/src/main/java/net/thisptr/phlegethon/storage",
        # "//server/src/main/java/net/thisptr/phlegethon/model",
        # "@maven//:org_springframework_spring_web",
        # "@maven//:com_fasterxml_jackson_core_jackson_databind",
        # "@maven//:com_zaxxer_HikariCP",
        # "@maven//:org_springframework_spring_beans",
        # "@maven//:org_springframework_spring_context",
        # "@maven//:com_google_guava_guava",
        # "@maven//:com_fasterxml_jackson_core_jackson_databind",
    ],
)
