java_library(
    name = "jfr",
    srcs = glob(["*.java"]),
    deps = [
        "//server/src/main/java/net/thisptr/phlegethon/blob",
        "//server/src/main/java/net/thisptr/phlegethon/misc",
        "@maven//:com_google_errorprone_error_prone_annotations",
        "@maven//:joda_time_joda_time",
    ],
)
